// src/lib/components/layout/Navbar.svelte
<script lang="ts">
  import { Bell, MessageCircle, Palette, Settings, LogOut, Search, User } from 'lucide-svelte'
  import { themeStore } from '$lib/stores/theme'
  import { currentProfile } from '$lib/stores/auth'
  import { t, locale, LOCALE_LABELS, LOCALE_COUNTRY, type Locale } from '$lib/i18n'
  import { APP_NAME } from '$lib/constants'
  import type { Theme } from '$lib/types'

  interface Props {
    unreadNotificationsCount?: number
    unreadMessagesCount?: number
  }

  let {
    unreadNotificationsCount = 0,
    unreadMessagesCount = 0
  }: Props = $props()

  const themes: Theme[] = ['green', 'dark', 'vivid', 'minimal']
  const locales = Object.keys(LOCALE_LABELS) as Locale[]

  let showLangMenu = $state(false)
  let showUserMenu = $state(false)

  function cycleTheme() {
    const idx = themes.indexOf(
      document.documentElement.className.replace('theme-', '') as Theme
    )
    themeStore.setTheme(themes[(idx + 1) % themes.length])
  }

  function selectLocale(l: Locale) {
    locale.setLocale(l)
    showLangMenu = false
  }
</script>

<nav class="navbar">
  <div class="inner">
    <!-- Logo -->
    <a href="/feed" class="logo">
      <span class="star">★</span>
      <span class="name">{APP_NAME}</span>
      <span class="beta">beta</span>
    </a>

    <!-- Search -->
    <a href="/search" class="search-bar" aria-label={$t('nav_search')}>
      <Search size={13} strokeWidth={2} />
      <span>{$t('nav_search')}…</span>
    </a>

    <!-- Right actions -->
    <div class="actions">
      <!-- Lang -->
      <div class="rel">
        <button class="btn-icon" onclick={() => { showLangMenu = !showLangMenu; showUserMenu = false }}
          title={$t('nav_change_lang')}>
          {#if LOCALE_COUNTRY[$locale]}
            <span class="fi fi-{LOCALE_COUNTRY[$locale]} flag-icon"></span>
          {:else}
            <span class="eo-badge">EO</span>
          {/if}
        </button>
        {#if showLangMenu}
          <button class="veil" onclick={() => (showLangMenu = false)} tabindex="-1" aria-hidden="true"></button>
          <div class="menu" role="menu">
            {#each locales as l}
              <button class="menu-row {$locale === l ? 'on' : ''}" onclick={() => selectLocale(l)} role="menuitem">
                {#if LOCALE_COUNTRY[l]}
                  <span class="fi fi-{LOCALE_COUNTRY[l]} flag-icon"></span>
                {:else}
                  <span class="eo-badge">EO</span>
                {/if}
                <span>{LOCALE_LABELS[l]}</span>
                {#if $locale === l}<span class="tick">✓</span>{/if}
              </button>
            {/each}
          </div>
        {/if}
      </div>

      <button class="btn-icon" onclick={cycleTheme} title={$t('nav_change_theme')}>
        <Palette size={16} strokeWidth={1.75} />
      </button>

      <a href="/notifications" class="btn-icon rel" title={$t('nav_notifications')}>
        <Bell size={16} strokeWidth={1.75} />
        {#if unreadNotificationsCount > 0}
          <span class="dot">{unreadNotificationsCount > 9 ? '9+' : unreadNotificationsCount}</span>
        {/if}
      </a>

      <a href="/messages" class="btn-icon rel" title={$t('nav_messages')}>
        <MessageCircle size={16} strokeWidth={1.75} />
        {#if unreadMessagesCount > 0}
          <span class="dot">{unreadMessagesCount > 9 ? '9+' : unreadMessagesCount}</span>
        {/if}
      </a>

      <!-- Avatar -->
      {#if $currentProfile}
        <div class="rel">
          <button class="avatar-wrap" onclick={() => { showUserMenu = !showUserMenu; showLangMenu = false }}>
            <img
              src={$currentProfile.avatar_url || `https://ui-avatars.com/api/?name=${encodeURIComponent($currentProfile.display_name)}&background=16a34a&color=fff`}
              alt={$currentProfile.display_name}
              class="avatar"
            />
          </button>
          {#if showUserMenu}
            <button class="veil" onclick={() => (showUserMenu = false)} tabindex="-1" aria-hidden="true"></button>
            <div class="menu menu-right" role="menu">
              <div class="menu-profile">
                <span class="mp-name">{$currentProfile.display_name}</span>
                <span class="mp-user">@{$currentProfile.username}</span>
              </div>
              <div class="sep"></div>
              <a href="/profile/{$currentProfile.username}" class="menu-row" onclick={() => showUserMenu = false}>
                <User size={13} strokeWidth={1.75} /> {$t('nav_profile')}
              </a>
              <a href="/settings" class="menu-row" onclick={() => showUserMenu = false}>
                <Settings size={13} strokeWidth={1.75} /> {$t('nav_settings')}
              </a>
              <div class="sep"></div>
              <form method="POST" action="/auth/logout">
                <button class="menu-row menu-danger" type="submit">
                  <LogOut size={13} strokeWidth={1.75} /> {$t('nav_logout')}
                </button>
              </form>
            </div>
          {/if}
        </div>
      {/if}
    </div>
  </div>
</nav>

<style>
  .navbar {
    position: sticky;
    top: 0;
    z-index: 100;
    background: var(--color-bg);
    border-bottom: 1px solid var(--color-border);
  }

  .inner {
    max-width: 1100px;
    margin: 0 auto;
    padding: 0 0.75rem;
    height: 52px;
    display: flex;
    align-items: center;
    gap: 0.5rem;
  }

  @media (min-width: 480px) {
    .inner { padding: 0 1.5rem; gap: 1rem; }
  }

  /* Logo */
  .logo {
    display: flex;
    align-items: center;
    gap: 0.4rem;
    text-decoration: none;
    flex-shrink: 0;
  }

  .star {
    font-size: 1.3rem;
    color: var(--color-primary);
    line-height: 1;
  }

  .name {
    font-size: 0.95rem;
    font-weight: 700;
    letter-spacing: -0.02em;
    color: var(--color-text);
    display: none;
  }

  @media (min-width: 520px) { .name { display: block; } }

  .beta {
    font-size: 0.6rem;
    font-weight: 700;
    letter-spacing: 0.05em;
    text-transform: uppercase;
    color: var(--color-primary);
    background: var(--color-primary-dim);
    border: 1px solid color-mix(in srgb, var(--color-primary) 25%, transparent);
    padding: 0.1rem 0.35rem;
    border-radius: 99px;
    align-self: flex-start;
    margin-top: 2px;
  }

  /* Search */
  .search-bar {
    display: none;
    flex: 1;
    max-width: 260px;
    align-items: center;
    gap: 0.4rem;
    padding: 0.38rem 0.75rem;
    background: var(--color-surface-alt);
    border: 1px solid var(--color-border);
    border-radius: 6px;
    color: var(--color-text-muted);
    font-size: 0.8rem;
    text-decoration: none;
    transition: border-color 0.15s;
  }

  @media (min-width: 480px) { .search-bar { display: flex; } }

  .search-bar:hover { border-color: var(--color-primary); }

  /* Actions */
  .actions {
    display: flex;
    align-items: center;
    gap: 0.1rem;
    margin-left: auto;
  }

  .btn-icon {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 34px;
    height: 34px;
    border-radius: 6px;
    background: transparent;
    border: none;
    color: var(--color-text-muted);
    cursor: pointer;
    text-decoration: none;
    transition: background 0.12s, color 0.12s;
    position: relative;
  }

  .btn-icon:hover { background: var(--color-surface-alt); color: var(--color-text); }

  .flag-icon {
    width: 20px;
    height: 15px;
    border-radius: 2px;
    display: block;
    flex-shrink: 0;
    box-shadow: 0 0 0 1px rgba(0,0,0,0.1);
  }

  .eo-badge {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 20px;
    height: 15px;
    border-radius: 2px;
    background: #16a34a;
    color: #fff;
    font-size: 0.58rem;
    font-weight: 700;
    letter-spacing: 0.03em;
    flex-shrink: 0;
  }

  .dot {
    position: absolute;
    top: 4px;
    right: 4px;
    background: var(--color-danger);
    color: #fff;
    font-size: 0.58rem;
    font-weight: 700;
    min-width: 14px;
    height: 14px;
    padding: 0 3px;
    border-radius: 99px;
    display: flex;
    align-items: center;
    justify-content: center;
    border: 1.5px solid var(--color-bg);
  }

  /* Avatar */
  .avatar-wrap {
    background: none;
    border: none;
    padding: 0;
    cursor: pointer;
    border-radius: 99px;
    display: flex;
  }

  .avatar {
    width: 30px;
    height: 30px;
    border-radius: 99px;
    object-fit: cover;
    border: 1.5px solid var(--color-border);
    transition: border-color 0.15s;
  }

  .avatar-wrap:hover .avatar { border-color: var(--color-primary); }

  /* Dropdown */
  .rel { position: relative; }

  .veil {
    position: fixed;
    inset: 0;
    z-index: 90;
    background: transparent;
    border: none;
    cursor: default;
    padding: 0;
  }

  .menu {
    position: absolute;
    top: calc(100% + 8px);
    right: 0;
    z-index: 100;
    background: var(--color-bg);
    border: 1px solid var(--color-border);
    border-radius: 10px;
    min-width: 168px;
    padding: 0.35rem;
    animation: pop 0.12s ease;
  }

  .menu-right { right: 0; }

  @keyframes pop {
    from { opacity: 0; transform: translateY(-4px); }
    to   { opacity: 1; transform: translateY(0); }
  }

  .menu-profile {
    padding: 0.5rem 0.6rem 0.35rem;
    display: flex;
    flex-direction: column;
    gap: 1px;
  }

  .mp-name { font-size: 0.825rem; font-weight: 600; color: var(--color-text); }
  .mp-user { font-size: 0.75rem; color: var(--color-text-muted); }

  .sep {
    height: 1px;
    background: var(--color-border);
    margin: 0.3rem 0;
  }

  .menu-row {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    width: 100%;
    padding: 0.42rem 0.6rem;
    border: none;
    background: transparent;
    color: var(--color-text-muted);
    font-size: 0.825rem;
    font-family: inherit;
    cursor: pointer;
    border-radius: 6px;
    transition: background 0.1s, color 0.1s;
    text-decoration: none;
    text-align: left;
  }

  .menu-row:hover { background: var(--color-surface-alt); color: var(--color-text); }
  .menu-row.on    { color: var(--color-primary); font-weight: 600; }
  .menu-danger:hover { color: var(--color-danger); }

  .tick { margin-left: auto; font-size: 0.75rem; }
</style>

// src/components/layout/Navbar.tsx
import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { Bell, MessageCircle, Palette, Settings, LogOut, Search, User } from 'lucide-react'
import { useTranslation } from 'react-i18next'
import { useThemeStore } from '@/stores/theme'
import { useAuthStore } from '@/stores/auth'
import { supabase } from '@/lib/supabase/client'
import { LOCALE_LABELS, LOCALE_COUNTRY, type Locale } from '@/lib/i18n'
import { APP_NAME } from '@/lib/constants'
import type { Theme } from '@/lib/types'
import i18n from '@/lib/i18n'
import { routes } from '@/lib/routes'
import { hasRequiredRole } from '@/lib/utils'

const THEMES: Theme[] = ['green', 'dark', 'vivid', 'minimal']
const LOCALES = Object.keys(LOCALE_LABELS) as Locale[]

interface NavbarProps {
  unreadNotificationsCount?: number
  unreadMessagesCount?: number
}

export function Navbar({ unreadNotificationsCount = 0, unreadMessagesCount = 0 }: NavbarProps) {
  const { t } = useTranslation()
  const { theme, setTheme } = useThemeStore()
  const profile = useAuthStore((s) => s.profile)
  const clearAuth = useAuthStore((s) => s.clear)
  const navigate = useNavigate()
  const [showLangMenu, setShowLangMenu] = useState(false)
  const [showUserMenu, setShowUserMenu] = useState(false)
  const locale = i18n.language as Locale
  const canAccessAdmin = profile ? hasRequiredRole(profile.role, 'moderator') : false

  function cycleTheme() {
    const idx = THEMES.indexOf(theme)
    setTheme(THEMES[(idx + 1) % THEMES.length])
  }

  function selectLocale(l: Locale) {
    i18n.changeLanguage(l)
    setShowLangMenu(false)
  }

  async function handleLogout() {
    await supabase.auth.signOut()
    clearAuth()
    navigate(routes.login)
  }

  return (
    <nav className="sticky top-0 z-[100] bg-[var(--color-bg)] border-b border-[var(--color-border)]">
      <div className="max-w-[1100px] mx-auto px-3 sm:px-6 h-[52px] flex items-center gap-2 sm:gap-4">

        {/* Logo */}
        <Link to={routes.feed} className="flex items-center gap-1.5 no-underline flex-shrink-0">
          <span className="text-[1.3rem] leading-none text-[var(--color-primary)]">★</span>
          <span className="hidden sm:block text-[0.95rem] font-bold tracking-tight text-[var(--color-text)]">
            {APP_NAME}
          </span>
          <span className="text-[0.6rem] font-bold tracking-wider uppercase text-[var(--color-primary)] bg-[var(--color-primary-dim)] border border-[color-mix(in_srgb,var(--color-primary)_25%,transparent)] px-1.5 py-0.5 rounded-full self-start mt-0.5">
            beta
          </span>
        </Link>

        {/* Search */}
        <Link
          to={routes.search}
          className="hidden sm:flex flex-1 max-w-[260px] items-center gap-1.5 px-3 py-1.5 bg-[var(--color-surface-alt)] border border-[var(--color-border)] rounded-[6px] text-[var(--color-text-muted)] text-[0.8rem] no-underline hover:border-[var(--color-primary)] transition-colors"
        >
          <Search size={13} strokeWidth={2} />
          <span>{t('nav_search')}…</span>
        </Link>

        {/* Right actions */}
        <div className="flex items-center gap-0.5 ml-auto">

          {/* Lang picker */}
          <div className="relative">
            <button
              className="flex items-center justify-center w-[34px] h-[34px] rounded-[6px] bg-transparent border-0 text-[var(--color-text-muted)] cursor-pointer hover:bg-[var(--color-surface-alt)] hover:text-[var(--color-text)] transition-all"
              title={t('nav_change_lang')}
              onClick={() => { setShowLangMenu(!showLangMenu); setShowUserMenu(false) }}
            >
              {LOCALE_COUNTRY[locale]
                ? <span className={`fi fi-${LOCALE_COUNTRY[locale]} block w-5 h-[15px] rounded-[2px] shadow-[0_0_0_1px_rgba(0,0,0,0.1)]`} />
                : <span className="inline-flex items-center justify-center w-5 h-[15px] rounded-[2px] bg-[#16a34a] text-white text-[0.58rem] font-bold">EO</span>
              }
            </button>
            {showLangMenu && (
              <>
                <button className="fixed inset-0 z-[90] bg-transparent border-0 cursor-default p-0" onClick={() => setShowLangMenu(false)} tabIndex={-1} aria-hidden />
                <div className="absolute top-[calc(100%+8px)] right-0 z-[100] bg-[var(--color-bg)] border border-[var(--color-border)] rounded-[10px] min-w-[168px] p-1.5 shadow-lg animate-[pop_0.12s_ease]">
                  {LOCALES.map((l) => (
                    <button
                      key={l}
                      onClick={() => selectLocale(l)}
                      className={`flex items-center gap-2 w-full px-2.5 py-[0.42rem] border-0 text-left text-[0.825rem] font-[inherit] cursor-pointer rounded-[6px] transition-all no-underline ${locale === l ? 'text-[var(--color-primary)] font-semibold' : 'text-[var(--color-text-muted)] hover:bg-[var(--color-surface-alt)] hover:text-[var(--color-text)]'}`}
                    >
                      {LOCALE_COUNTRY[l]
                        ? <span className={`fi fi-${LOCALE_COUNTRY[l]} block w-5 h-[15px] rounded-[2px] shadow-[0_0_0_1px_rgba(0,0,0,0.1)] flex-shrink-0`} />
                        : <span className="inline-flex items-center justify-center w-5 h-[15px] rounded-[2px] bg-[#16a34a] text-white text-[0.58rem] font-bold flex-shrink-0">EO</span>
                      }
                      <span>{LOCALE_LABELS[l]}</span>
                      {locale === l && <span className="ml-auto text-[0.75rem]">✓</span>}
                    </button>
                  ))}
                </div>
              </>
            )}
          </div>

          {/* Theme cycle */}
          <button
            className="flex items-center justify-center w-[34px] h-[34px] rounded-[6px] bg-transparent border-0 text-[var(--color-text-muted)] cursor-pointer hover:bg-[var(--color-surface-alt)] hover:text-[var(--color-text)] transition-all"
            title={t('nav_change_theme')}
            onClick={cycleTheme}
          >
            <Palette size={16} strokeWidth={1.75} />
          </button>

          {/* Notifications */}
          <Link
            to={routes.notifications}
            title={t('nav_notifications')}
            className="relative flex items-center justify-center w-[34px] h-[34px] rounded-[6px] bg-transparent text-[var(--color-text-muted)] no-underline hover:bg-[var(--color-surface-alt)] hover:text-[var(--color-text)] transition-all"
          >
            <Bell size={16} strokeWidth={1.75} />
            {unreadNotificationsCount > 0 && (
              <span className="absolute top-1 right-1 bg-[var(--color-danger)] text-white text-[0.58rem] font-bold min-w-[14px] h-[14px] px-[3px] rounded-full flex items-center justify-center border-[1.5px] border-[var(--color-bg)]">
                {unreadNotificationsCount > 9 ? '9+' : unreadNotificationsCount}
              </span>
            )}
          </Link>

          {/* Messages */}
          <Link
            to={routes.messages}
            title={t('nav_messages')}
            className="relative flex items-center justify-center w-[34px] h-[34px] rounded-[6px] bg-transparent text-[var(--color-text-muted)] no-underline hover:bg-[var(--color-surface-alt)] hover:text-[var(--color-text)] transition-all"
          >
            <MessageCircle size={16} strokeWidth={1.75} />
            {unreadMessagesCount > 0 && (
              <span className="absolute top-1 right-1 bg-[var(--color-danger)] text-white text-[0.58rem] font-bold min-w-[14px] h-[14px] px-[3px] rounded-full flex items-center justify-center border-[1.5px] border-[var(--color-bg)]">
                {unreadMessagesCount > 9 ? '9+' : unreadMessagesCount}
              </span>
            )}
          </Link>

          {/* Avatar / user menu */}
          {profile && (
            <div className="relative">
              <button
                className="p-0 border-0 bg-transparent cursor-pointer rounded-full flex"
                onClick={() => { setShowUserMenu(!showUserMenu); setShowLangMenu(false) }}
              >
                <img
                  src={profile.avatar_url || `https://ui-avatars.com/api/?name=${encodeURIComponent(profile.display_name)}&background=16a34a&color=fff`}
                  alt={profile.display_name}
                  className="w-[30px] h-[30px] rounded-full object-cover border-[1.5px] border-[var(--color-border)] hover:border-[var(--color-primary)] transition-colors"
                />
              </button>
              {showUserMenu && (
                <>
                  <button className="fixed inset-0 z-[90] bg-transparent border-0 cursor-default p-0" onClick={() => setShowUserMenu(false)} tabIndex={-1} aria-hidden />
                  <div className="absolute top-[calc(100%+8px)] right-0 z-[100] bg-[var(--color-bg)] border border-[var(--color-border)] rounded-[10px] min-w-[168px] p-1.5 shadow-lg animate-[pop_0.12s_ease]">
                    <div className="px-2.5 py-2 pb-1.5 flex flex-col gap-px">
                      <span className="text-[0.825rem] font-semibold text-[var(--color-text)]">{profile.display_name}</span>
                      <span className="text-[0.75rem] text-[var(--color-text-muted)]">@{profile.username}</span>
                    </div>
                    <div className="h-px bg-[var(--color-border)] my-1.5" />
                    <Link to={routes.profile(profile.username)} onClick={() => setShowUserMenu(false)}
                      className="flex items-center gap-2 w-full px-2.5 py-[0.42rem] text-[var(--color-text-muted)] text-[0.825rem] no-underline rounded-[6px] hover:bg-[var(--color-surface-alt)] hover:text-[var(--color-text)] transition-all">
                      <User size={13} strokeWidth={1.75} /> {t('nav_profile')}
                    </Link>
                    <Link to={routes.settings} onClick={() => setShowUserMenu(false)}
                      className="flex items-center gap-2 w-full px-2.5 py-[0.42rem] text-[var(--color-text-muted)] text-[0.825rem] no-underline rounded-[6px] hover:bg-[var(--color-surface-alt)] hover:text-[var(--color-text)] transition-all">
                      <Settings size={13} strokeWidth={1.75} /> {t('nav_settings')}
                    </Link>
                    {canAccessAdmin && (
                      <Link to={routes.admin} onClick={() => setShowUserMenu(false)}
                        className="flex items-center gap-2 w-full px-2.5 py-[0.42rem] text-[var(--color-text-muted)] text-[0.825rem] no-underline rounded-[6px] hover:bg-[var(--color-surface-alt)] hover:text-[var(--color-text)] transition-all">
                        <User size={13} strokeWidth={1.75} /> {t('admin_panel')}
                      </Link>
                    )}
                    <div className="h-px bg-[var(--color-border)] my-1.5" />
                    <button onClick={handleLogout}
                      className="flex items-center gap-2 w-full px-2.5 py-[0.42rem] text-[var(--color-text-muted)] text-[0.825rem] font-[inherit] border-0 bg-transparent cursor-pointer text-left rounded-[6px] hover:bg-[var(--color-surface-alt)] hover:text-[var(--color-danger)] transition-all">
                      <LogOut size={13} strokeWidth={1.75} /> {t('nav_logout')}
                    </button>
                  </div>
                </>
              )}
            </div>
          )}
        </div>
      </div>
    </nav>
  )
}
