// src/lib/components/layout/Sidebar.svelte
<script lang="ts">
  import { CATEGORIES } from '$lib/constants'
  import { t, type TranslationKey } from '$lib/i18n'
  import { CATEGORY_ICONS, CATEGORY_COLORS } from '$lib/icons'
  import { page } from '$app/state'
  import type { Category } from '$lib/types'

  interface Props {
    categories?: Category[]
    activeSlug?: string
  }

  let { categories = [], activeSlug = '' }: Props = $props()

  const path = $derived(page.url?.pathname ?? '')
</script>

<aside class="sidebar">
  <nav>
    <a href="/feed" class="link" class:active={path === '/feed'}>
      {$t('nav_home')}
    </a>
    <a href="/feed?filter=following" class="link" class:active={path.includes('following')}>
      {$t('nav_following')}
    </a>
  </nav>

  <div class="section">
    <p class="label">{$t('nav_categories')}</p>
    <nav>
      {#each CATEGORIES as cat}
        {@const found = categories.find((c) => c.slug === cat.slug)}
        {@const CatIcon = CATEGORY_ICONS[cat.slug]}
        <a
          href="/category/{cat.slug}"
          class="link cat"
          class:active={activeSlug === cat.slug || path.includes(`/category/${cat.slug}`)}
        >
          {#if CatIcon}<span class="icon" style="color: {CATEGORY_COLORS[cat.slug]}"><CatIcon size={15} strokeWidth={1.75} /></span>{/if}
          <span class="cat-name">{$t(('cat_name_' + cat.slug) as TranslationKey)}</span>
        </a>
      {/each}
    </nav>
  </div>
</aside>

<style>
  .sidebar {
    width: 210px;
    flex-shrink: 0;
    display: flex;
    flex-direction: column;
    gap: 1.5rem;
  }

  .section { display: flex; flex-direction: column; gap: 0.5rem; }

  .label {
    font-size: 0.67rem;
    font-weight: 600;
    letter-spacing: 0.09em;
    text-transform: uppercase;
    color: var(--color-text-muted);
    padding: 0 0.5rem;
    margin: 0;
  }

  nav { display: flex; flex-direction: column; }

  .link {
    display: flex;
    align-items: center;
    gap: 0.55rem;
    padding: 0.42rem 0.5rem;
    font-size: 0.875rem;
    font-weight: 500;
    color: var(--color-text-muted);
    text-decoration: none;
    border-radius: 6px;
    transition: color 0.12s, background 0.12s;
  }

  .link:hover { color: var(--color-text); background: var(--color-surface-alt); }
  .link.active { color: var(--color-primary); font-weight: 600; }

  .icon { font-size: 0.9rem; width: 18px; text-align: center; flex-shrink: 0; }

  .cat-name { flex: 1; min-width: 0; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
</style>

// src/components/layout/Sidebar.tsx
import { Link, useLocation } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { CATEGORIES } from '@/lib/constants'
import { CATEGORY_ICONS, CATEGORY_COLORS } from '@/lib/icons'
import type { Category } from '@/lib/types'
import type { TranslationKey } from '@/lib/i18n'
import { feedWithFilter, routes } from '@/lib/routes'

interface SidebarProps {
  categories?: Category[]
}

export function Sidebar({ categories = [] }: SidebarProps) {
  const { t } = useTranslation()
  const { pathname } = useLocation()

  return (
    <aside className="w-[210px] flex-shrink-0 flex flex-col gap-6">
      <nav className="flex flex-col">
        <Link
          to={routes.feed}
          className={`flex items-center gap-2 px-2 py-[0.42rem] text-[0.875rem] font-medium rounded-[6px] no-underline transition-all ${pathname === routes.feed ? 'text-[var(--color-primary)] font-semibold' : 'text-[var(--color-text-muted)] hover:text-[var(--color-text)] hover:bg-[var(--color-surface-alt)]'}`}
        >
          {t('nav_home')}
        </Link>
        <Link
          to={feedWithFilter('following')}
          className={`flex items-center gap-2 px-2 py-[0.42rem] text-[0.875rem] font-medium rounded-[6px] no-underline transition-all ${pathname === routes.feed ? 'text-[var(--color-primary)] font-semibold' : 'text-[var(--color-text-muted)] hover:text-[var(--color-text)] hover:bg-[var(--color-surface-alt)]'}`}
        >
          {t('nav_following')}
        </Link>
        <Link
          to={routes.communityChat}
          className={`flex items-center gap-2 px-2 py-[0.42rem] text-[0.875rem] font-medium rounded-[6px] no-underline transition-all ${pathname === routes.communityChat ? 'text-[var(--color-primary)] font-semibold' : 'text-[var(--color-text-muted)] hover:text-[var(--color-text)] hover:bg-[var(--color-surface-alt)]'}`}
        >
          {t('nav_chat', { defaultValue: 'Babilejo' })}
        </Link>
      </nav>

      <div className="flex flex-col gap-2">
        <p className="text-[0.67rem] font-semibold tracking-[0.09em] uppercase text-[var(--color-text-muted)] px-2 m-0">
          {t('nav_categories')}
        </p>
        <nav className="flex flex-col">
          {CATEGORIES.map((cat) => {
            const Icon = CATEGORY_ICONS[cat.slug]
            const isActive = pathname.includes(`/kategorio/${cat.slug}`)
            return (
              <Link
                key={cat.slug}
                to={routes.category(cat.slug)}
                className={`flex items-center gap-2 px-2 py-[0.42rem] text-[0.875rem] font-medium rounded-[6px] no-underline transition-all ${isActive ? 'text-[var(--color-primary)] font-semibold' : 'text-[var(--color-text-muted)] hover:text-[var(--color-text)] hover:bg-[var(--color-surface-alt)]'}`}
              >
                {Icon && (
                  <span className="w-[18px] text-center flex-shrink-0" style={{ color: CATEGORY_COLORS[cat.slug] }}>
                    <Icon size={15} strokeWidth={1.75} />
                  </span>
                )}
                <span className="flex-1 min-w-0 whitespace-nowrap overflow-hidden text-ellipsis">
                  {t(('cat_name_' + cat.slug) as TranslationKey)}
                </span>
              </Link>
            )
          })}
        </nav>
      </div>
    </aside>
  )
}
