// src/components/ToastViewport.tsx
import { useEffect, useRef, useState } from 'react'
import { useToastStore, type Toast } from '@/stores/toasts'

function ToastItem({ toast, onRemove }: { toast: Toast; onRemove: (id: number) => void }) {
  const [visible, setVisible] = useState(false)

  useEffect(() => {
    const frame = requestAnimationFrame(() => setVisible(true))
    return () => cancelAnimationFrame(frame)
  }, [])

  const toneClasses = {
    success: 'border-[color-mix(in_srgb,var(--color-primary)_36%,transparent)] bg-[color-mix(in_srgb,var(--color-primary)_10%,var(--color-surface)_90%)]',
    error: 'border-[rgba(220,38,38,0.28)] bg-[#fff5f5] text-[#7f1d1d]',
    info: 'border-[color-mix(in_srgb,var(--color-primary)_24%,transparent)]',
  }[toast.tone]

  return (
    <div
      role={toast.tone === 'error' ? 'alert' : 'status'}
      className={`flex items-start gap-3 px-[0.95rem] py-[0.85rem] rounded-[1rem] border border-[var(--color-border)] bg-[color-mix(in_srgb,var(--color-surface)_92%,white_8%)] text-[var(--color-text)] shadow-[0_18px_40px_rgba(0,0,0,0.14)] pointer-events-auto backdrop-blur-[14px] transition-all duration-200 ${toneClasses} ${visible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-4'}`}
    >
      <p className="m-0 flex-1 text-[0.88rem] leading-[1.45]">{toast.message}</p>
      <button
        type="button"
        onClick={() => onRemove(toast.id)}
        aria-label="Dismiss notification"
        className="border-0 bg-transparent text-inherit text-base leading-none cursor-pointer p-[0.05rem] opacity-70 hover:opacity-100"
      >
        ×
      </button>
    </div>
  )
}

export function ToastViewport() {
  const { toasts, remove } = useToastStore()

  return (
    <div
      aria-live="polite"
      aria-atomic="true"
      className="fixed right-4 bottom-[5.25rem] md:bottom-5 z-[1200] flex flex-col gap-[0.65rem] w-[min(24rem,calc(100vw-1.5rem))] pointer-events-none"
    >
      {toasts.map((toast) => (
        <ToastItem key={toast.id} toast={toast} onRemove={remove} />
      ))}
    </div>
  )
}

// src/lib/components/ToastViewport.svelte
<script lang="ts">
  import { fly, fade } from 'svelte/transition'
  import { toastStore } from '$lib/stores/toasts'
</script>

<div class="toast-viewport" aria-live="polite" aria-atomic="true">
  {#each $toastStore as toast (toast.id)}
    <div
      class="toast {toast.tone}"
      role={toast.tone === 'error' ? 'alert' : 'status'}
      in:fly={{ y: 16, duration: 180 }}
      out:fade={{ duration: 160 }}
    >
      <p>{toast.message}</p>
      <button
        type="button"
        class="close"
        aria-label="Dismiss notification"
        onclick={() => toastStore.remove(toast.id)}
      >
        ×
      </button>
    </div>
  {/each}
</div>

<style>
  .toast-viewport {
    position: fixed;
    right: 1rem;
    bottom: 5.25rem;
    z-index: 1200;
    display: flex;
    flex-direction: column;
    gap: 0.65rem;
    width: min(24rem, calc(100vw - 1.5rem));
    pointer-events: none;
  }

  .toast {
    display: flex;
    align-items: flex-start;
    gap: 0.75rem;
    padding: 0.85rem 0.95rem;
    border-radius: 1rem;
    border: 1px solid var(--color-border);
    background: color-mix(in srgb, var(--color-surface) 92%, white 8%);
    color: var(--color-text);
    box-shadow: 0 18px 40px rgba(0, 0, 0, 0.14);
    pointer-events: auto;
    backdrop-filter: blur(14px);
  }

  .toast.success {
    border-color: color-mix(in srgb, var(--color-primary) 36%, transparent);
    background: color-mix(in srgb, var(--color-primary) 10%, var(--color-surface) 90%);
  }

  .toast.error {
    border-color: rgba(220, 38, 38, 0.28);
    background: #fff5f5;
    color: #7f1d1d;
  }

  .toast.info {
    border-color: color-mix(in srgb, var(--color-primary) 24%, transparent);
  }

  p {
    margin: 0;
    flex: 1;
    font-size: 0.88rem;
    line-height: 1.45;
  }

  .close {
    border: none;
    background: transparent;
    color: inherit;
    font-size: 1rem;
    line-height: 1;
    cursor: pointer;
    padding: 0.05rem;
    opacity: 0.72;
  }

  .close:hover {
    opacity: 1;
  }

  @media (min-width: 768px) {
    .toast-viewport {
      bottom: 1.25rem;
    }
  }
</style>
