// src/components/layout/MobileNav.tsx
import { Link, useLocation } from 'react-router-dom'
import { Home, Search, Bell, MessageCircle, User } from 'lucide-react'
import { useAuthStore } from '@/stores/auth'
import { routes } from '@/lib/routes'

interface MobileNavProps {
  unreadNotificationsCount?: number
  unreadMessagesCount?: number
}

export function MobileNav({ unreadNotificationsCount = 0, unreadMessagesCount = 0 }: MobileNavProps) {
  const { pathname } = useLocation()
  const profile = useAuthStore((s) => s.profile)

  return (
    <nav className="flex md:hidden fixed bottom-0 left-0 right-0 z-[90] bg-[var(--color-bg)] border-t border-[var(--color-border)] px-2 pb-[calc(env(safe-area-inset-bottom,0px)+0.35rem)]">
      <Link to={routes.feed} className={`flex-1 flex items-center justify-center py-2.5 no-underline transition-colors ${pathname === routes.feed ? 'text-[var(--color-primary)]' : 'text-[var(--color-text-muted)]'}`}>
        <Home size={21} strokeWidth={pathname === routes.feed ? 2.5 : 1.75} />
      </Link>

      <Link to={routes.search} className={`flex-1 flex items-center justify-center py-2.5 no-underline transition-colors ${pathname === routes.search ? 'text-[var(--color-primary)]' : 'text-[var(--color-text-muted)]'}`}>
        <Search size={21} strokeWidth={pathname === routes.search ? 2.5 : 1.75} />
      </Link>

      <Link to={routes.notifications} className={`relative flex-1 flex items-center justify-center py-2.5 no-underline transition-colors ${pathname === routes.notifications ? 'text-[var(--color-primary)]' : 'text-[var(--color-text-muted)]'}`}>
        <Bell size={21} strokeWidth={pathname === routes.notifications ? 2.5 : 1.75} />
        {unreadNotificationsCount > 0 && (
          <span className="absolute top-1.5 right-[calc(50%-18px)] bg-[var(--color-danger)] text-white text-[0.58rem] font-bold min-w-[14px] h-[14px] px-[3px] rounded-full flex items-center justify-center border-[1.5px] border-[var(--color-bg)]">
            {unreadNotificationsCount > 9 ? '9+' : unreadNotificationsCount}
          </span>
        )}
      </Link>

      <Link to={routes.messages} className={`relative flex-1 flex items-center justify-center py-2.5 no-underline transition-colors ${pathname === routes.messages ? 'text-[var(--color-primary)]' : 'text-[var(--color-text-muted)]'}`}>
        <MessageCircle size={21} strokeWidth={pathname === routes.messages ? 2.5 : 1.75} />
        {unreadMessagesCount > 0 && (
          <span className="absolute top-1.5 right-[calc(50%-18px)] bg-[var(--color-danger)] text-white text-[0.58rem] font-bold min-w-[14px] h-[14px] px-[3px] rounded-full flex items-center justify-center border-[1.5px] border-[var(--color-bg)]">
            {unreadMessagesCount > 9 ? '9+' : unreadMessagesCount}
          </span>
        )}
      </Link>

      <Link
        to={profile ? routes.profile(profile.username) : routes.feed}
        className={`flex-1 flex items-center justify-center py-2.5 no-underline transition-colors ${pathname.startsWith('/profilo') ? 'text-[var(--color-primary)]' : 'text-[var(--color-text-muted)]'}`}
      >
        <User size={21} strokeWidth={pathname.startsWith('/profilo') ? 2.5 : 1.75} />
      </Link>
    </nav>
  )
}

// src/lib/components/layout/MobileNav.svelte
<script lang="ts">
  import { Home, Search, Bell, MessageCircle, User } from 'lucide-svelte'
  import { page } from '$app/state'

  interface Props {
    unreadNotificationsCount?: number
    unreadMessagesCount?: number
  }

  let {
    unreadNotificationsCount = 0,
    unreadMessagesCount = 0
  }: Props = $props()

  const path = $derived(page.url?.pathname ?? '')
</script>

<nav class="mobile-nav">
  <a href="/feed"          class="item" class:on={path === '/feed'}>
    <Home size={21} strokeWidth={path === '/feed' ? 2.5 : 1.75} />
  </a>
  <a href="/search"        class="item" class:on={path === '/search'}>
    <Search size={21} strokeWidth={path === '/search' ? 2.5 : 1.75} />
  </a>
  <a href="/notifications" class="item notif" class:on={path === '/notifications'}>
    <Bell size={21} strokeWidth={path === '/notifications' ? 2.5 : 1.75} />
    {#if unreadNotificationsCount > 0}
      <span class="badge">{unreadNotificationsCount > 9 ? '9+' : unreadNotificationsCount}</span>
    {/if}
  </a>
  <a href="/messages" class="item notif" class:on={path === '/messages'}>
    <MessageCircle size={21} strokeWidth={path === '/messages' ? 2.5 : 1.75} />
    {#if unreadMessagesCount > 0}
      <span class="badge">{unreadMessagesCount > 9 ? '9+' : unreadMessagesCount}</span>
    {/if}
  </a>
  <a href="/profile/me"    class="item" class:on={path.startsWith('/profile')}>
    <User size={21} strokeWidth={path.startsWith('/profile') ? 2.5 : 1.75} />
  </a>
</nav>

<style>
  .mobile-nav {
    display: flex;
    position: fixed;
    bottom: 0;
    left: 0;
    right: 0;
    z-index: 90;
    background: var(--color-bg);
    border-top: 1px solid var(--color-border);
    padding: 0 0.5rem calc(env(safe-area-inset-bottom, 0px) + 0.35rem);
  }

  @media (min-width: 768px) { .mobile-nav { display: none; } }

  .item {
    flex: 1;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 0.6rem 0.25rem;
    text-decoration: none;
    color: var(--color-text-muted);
    position: relative;
    transition: color 0.15s;
  }

  .item.on { color: var(--color-primary); }

  .notif { position: relative; }

  .badge {
    position: absolute;
    top: 6px;
    right: calc(50% - 18px);
    background: var(--color-danger);
    color: #fff;
    font-size: 0.58rem;
    font-weight: 700;
    min-width: 14px;
    height: 14px;
    padding: 0 3px;
    border-radius: 99px;
    display: flex;
    align-items: center;
    justify-content: center;
    border: 1.5px solid var(--color-bg);
  }
</style>
